title:            Brian Maier Jr. | Louisville Web Design
tagline:          Everyone needs a good web guy.
description:      Brian is a web designer/developer from Louisville who specializes in clean and beatuiful user interfaces.
#Comment out url when working locally to resolve base urls correctly
url: http://blog.brianmaierjr.com

# Owner/author information
owner:
  name:           Brian Maier Jr.
  avatar:         avatar.png
  bio:            Designer/Developer/Dad/Idiot
  email:          brimaidesigns@gmail.com
  twitter:        brianmaierjr
  github:         brianmaierjr
  instagram:      brian_maier_jr   
  dribbble:       brianmaierjr
  disqus:         brianmaierjr
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
    external: true
  - title: Articles
    url: /articles
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
