name:             Brian Maier Jr. | Designer & Developer
title:            Brian Maier Jr. | Designer & Developer
description:      Online home of midwest designer & developer Brian Maier Jr.
markdown:         redcarpet
pygments:         true
permalink: 		   /portfolio-old/:categories/:title
include:          [.htaccess]
url:               http://brianmaierjr.github.com/portfolio-old
categories: 

# Links to include in top navigation 
links:
  - title: 02. About 
    url: /portfolio-old/about
  - title: 03. Articles
    url: /portfolio-old/articles
  - title: 04. Contact Me 
    url: mailto:brimaidesigns@gmail.com

