name:             Brian Maier Jr. | Designer & Developer
title:            Brian Maier Jr. | Designer & Developer
description:      Louisville Web Design by Brian Maier Jr.
markdown:         redcarpet
pygments:         true
#Comment out url when working locally to resolve base urls correctly
# url: http://blog.brianmaierjr.com

# Links to include in top navigation
links:
  - title: 02. About
    url: /about
  - title: 03. Articles
    url: /articles
  - title: 04. Portfolio
    url: /portfolio

