title:            Brian Maier Jr.
description:      Louisville Web Design by Brian Maier Jr.
#Comment out url when working locally to resolve base urls correctly
#url: http://blog.brianmaierjr.com

# Owner/author information
owner:
  name:           Brian Maier Jr.
  email:          brimaidesigns@gmail.com
  twitter:        brianmaierjr      
  dribbble:       brianmaierjr 


# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Blog
    url: /blog